/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AppointmentId = IDL.Nat;
export const Appointment = IDL.Record({
  'treatmentNeeded' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'preferredTime' : Time,
  'patientName' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'bookAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'getAllAppointments' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(AppointmentId, Appointment))],
      ['query'],
    ),
  'getAppointment' : IDL.Func([AppointmentId], [Appointment], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AppointmentId = IDL.Nat;
  const Appointment = IDL.Record({
    'treatmentNeeded' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'preferredTime' : Time,
    'patientName' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'bookAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'getAllAppointments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(AppointmentId, Appointment))],
        ['query'],
      ),
    'getAppointment' : IDL.Func([AppointmentId], [Appointment], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };